name: deploy
on:
  push:
    branches:
      - master
      - init

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build & deploy
        env:
          BUILD_ID: ${{ github.sha }}
          ZEIT_TOKEN: ${{ secrets.ZEIT_TOKEN }}
        run: |
          yarn
          yarn bootstrap
          yarn docs:build
          now --token=$ZEIT_TOKEN --dev --confirm --force
